[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/firecracker-microvm/micro-http?branch=main"]
git = "https://github.com/firecracker-microvm/micro-http"
branch = "main"
replace-with = "vendored-sources"

[source."git+https://github.com/microsoft/igvm?branch=main"]
git = "https://github.com/microsoft/igvm"
branch = "main"
replace-with = "vendored-sources"

[source."git+https://github.com/rust-vmm/acpi_tables?branch=main"]
git = "https://github.com/rust-vmm/acpi_tables"
branch = "main"
replace-with = "vendored-sources"

[source."git+https://github.com/rust-vmm/vm-fdt?branch=main"]
git = "https://github.com/rust-vmm/vm-fdt"
branch = "main"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"